Support custom patching of Redis source (#14)
This commit adds `REDIS_APPLY_PATCHES` so that we can work around
Redis build issues on macOS:
https://github.com/redis/redis/issues/12585

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -21,6 +21,10 @@ install_redis() {
     tar zxf $source_path || exit 1
     cd $(untar_path $install_type $version $tmp_download_dir)
 
+    if [[ -n "${REDIS_APPLY_PATCHES:-}" ]]; then
+      apply_patches "$(fetch_patches "$REDIS_APPLY_PATCHES")"
+    fi
+
     # set in os_based_configure_options
     # we unset it here because echo-ing changes the return value of the function
     unset ASDF_PKG_MISSING
@@ -70,5 +74,54 @@ get_download_url() {
   echo "https://download.redis.io/releases/redis-${version}.tar.gz"
 }
 
+
+fetch_patches() {
+  while read -r line; do
+    if [ "$line" = "" ]; then continue; fi
+    if [[ "$line" =~ ^[Hh][Tt][Tt][Pp][Ss]?:// ]]; then
+      >&2 echo "Using patch from URL: $line"
+      curl -fSs "$line" || exit 1
+    else
+      local abs_path
+      abs_path="$(get_absolute_path "$line")"
+      >&2 echo "Using local patch: $abs_path"
+      cat "$abs_path" || exit 1
+    fi
+  done <<< "$@"
+}
+
+
+get_absolute_path() {
+  local start_dir
+  local rel_path
+  local rel_dir
+  local rel_base
+
+  start_dir="$(pwd)"
+  rel_path="$1"
+  rel_dir="$(dirname "$rel_path")"
+  rel_base="$(basename "$rel_path")"
+
+  (
+    cd "$start_dir" \
+      && cd "$rel_dir" 2>/dev/null \
+      && echo "$(pwd)/$rel_base" \
+      || echo "$rel_path"
+  )
+}
+
+
+apply_patches() {
+  patches="$1"
+
+  for patch_data in "${patches[@]}"; do
+    echo "$patch_data" | patch -p1
+    if [ $? -eq 0 ]; then
+      echo "Patch applied successfully"
+    else
+      echo "Failed to apply patch: $patch_data"
+    fi
+  done
+}
 
 install_redis $ASDF_INSTALL_TYPE $ASDF_INSTALL_VERSION $ASDF_INSTALL_PATH
